import Config

# Configure your database
config :quantum_flow, QuantumFlow.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "quantum_flow_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :quantum_flow, QuantumFlowWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "your_secret_key_base_here",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :quantum_flow, QuantumFlowWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/quantum_flow_web/(live|views)/.*(ex)$",
      ~r"lib/quantum_flow_web/templates/.*(eex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :quantum_flow, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Orchestrator development configuration
config :quantum_flow, :orchestrator,
  # Enable debug logging for development
  debug: true,
  
  # More lenient timeouts for development
  timeout: 600_000,
  execution: %{
    timeout: 600_000,
    task_timeout: 60_000
  },
  
  # Enable all features for development
  features: %{
    monitoring: true,
    optimization: true,
    notifications: true,
    learning: true,
    real_time: true
  },
  
  # More verbose logging
  notifications: %{
    enabled: true,
    real_time: true,
    event_types: [:decomposition, :task, :workflow, :performance],
    queue_prefix: "orchestrator_dev",
    timeout: 10_000
  }