name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19.1'
        otp-version: '27.1'

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Install pgmq extension
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-server-dev-15 build-essential git
        git clone https://github.com/tembo-io/pgmq.git /tmp/pgmq
        cd /tmp/pgmq
        make
        sudo make install
        sudo -u postgres psql -c "CREATE EXTENSION pgmq;"

    - name: Create test database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE ex_pgflow;"

    - name: Run migrations
      run: |
        export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/ex_pgflow"
        mix ecto.migrate
      env:
        MIX_ENV: test

    - name: Run tests
      run: |
        export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/ex_pgflow"
        mix test
      env:
        MIX_ENV: test