name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.14.0
          otp-version: 26.0

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: deps
          key: "${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}"
          restore-keys: "${{ runner.os }}-mix-"

      - name: Install dependencies
        run: mix deps.get

      - name: Create test database
        run: |
          export PGPASSWORD=postgres
          psql -h localhost -U postgres -c "CREATE DATABASE ex_pgflow_test;"
          psql -h localhost -U postgres ex_pgflow_test -c "CREATE EXTENSION IF NOT EXISTS pgmq;"
        env:
          PGPASSWORD: postgres

      - name: Run tests
        run: mix test
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/ex_pgflow_test"

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run credo
        run: mix credo --strict

      - name: Run sobelow
        run: mix sobelow --exit-on-warning

      - name: Check dependencies
        run: mix deps.audit
