name: Publish to Hex.pm

on:
  push:
    tags:
      - 'v*'

jobs:
  # First job: Run CI tests
  ci:
    name: CI Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        # Official pgmq Docker image with PostgreSQL 15 + pgmq extension
        image: tembo/pgmq:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ex_pgflow_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19'
        otp-version: '28'

    - name: Verify PostgreSQL and pgmq are ready
      run: |
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -U postgres; do sleep 1; done
        # Create the database if it doesn't exist
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE IF NOT EXISTS ex_pgflow_test;"
        # pgmq extension is pre-installed in tembo/pgmq image
        PGPASSWORD=postgres psql -h localhost -U postgres -d ex_pgflow_test -c "CREATE EXTENSION IF NOT EXISTS pgmq;"

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ex_pgflow_test
        POSTGRES_HOST: localhost

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Run security audit
      run: mix sobelow --exit-on-warning

  # Second job: Require manual approval
  approve:
    name: Release Approval
    needs: ci
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Release approved
      run: echo "Release approved by ${{ github.actor }}"

  # Third job: Publish to Hex.pm
  publish:
    name: Publish to Hex.pm
    needs: [ci, approve]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19'
        otp-version: '28'

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Publish to Hex.pm
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}